"""dd acquisition_date  record at lands table

Revision ID: 275973b7ab37
Revises: 8d55620e479e
Create Date: 2025-09-18 22:57:23.108013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275973b7ab37'
down_revision: Union[str, None] = '8d55620e479e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('acquisition_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('land', 'acquisition_date')
    # ### end Alembic commands ###
