"""add in_procces record at lands table

Revision ID: 38319b5ed780
Revises: 754c12e83060
Create Date: 2025-09-18 15:43:45.008093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38319b5ed780'
down_revision: Union[str, None] = '754c12e83060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('in_procces', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('land', 'in_procces')
    # ### end Alembic commands ###
