"""add in_procces record at lands table

Revision ID: 8d55620e479e
Revises: 38319b5ed780
Create Date: 2025-09-18 16:01:03.963195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d55620e479e'
down_revision: Union[str, None] = '38319b5ed780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('land', 'in_procces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('in_procces', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
