"""update users table

Revision ID: f53b2421e61e
Revises: 7bbad50e9270
Create Date: 2025-09-17 14:39:21.101195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53b2421e61e'
down_revision: Union[str, None] = '7bbad50e9270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=250), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
